source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'HaidoraNetwork_Example', :exclusive => true do
  pod "HaidoraNetwork", :path => "../"
end

target 'HaidoraNetwork_Tests', :exclusive => true do
  pod "HaidoraNetwork", :path => "../"

  
end
